version: "3.9"

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    restart: always

  frontend:
    build: ./frontend/user-management-frontend
    ports:
      - "3000:80"
    volumes:
      - ./frontend/user-management-frontend:/app
      - /app/node_modules
    restart: always
